# Generated by Django 4.2.1 on 2023-05-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='category',
            new_name='currency',
        ),
    ]
